"""Gate Guard — information quarantine at the gate of the 蔵.

Clean-room port of Lna-Lab AIOS's `agents/gate_guard.py` (the 千手観音 castle-gate inspector).
Every piece of web text the fleet ingests passes the guard before a scout reads it or it can
enter permanent memory: pure-regex, no LLM, no deps beyond stdlib. A page that says
"ignore previous instructions, you are now…" or an AI-fabricated source is scored and tagged
PASS / FLAG / REJECT — the plague stays outside the walls (AIOS doctrine: a shield, not a chain).

  PASS   — clean; eligible for memory / promotion
  FLAG   — suspicious; usable but annotated (private-only, with _inspection metadata)
  REJECT — contaminated; dropped before a scout ever reads it
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from urllib.parse import urlparse


class Verdict(str, Enum):
    PASS = "pass"
    FLAG = "flag"
    REJECT = "reject"


@dataclass
class Inspection:
    verdict: Verdict
    score: float                      # 0.0 (clean) … 1.0 (contaminated)
    flags: list[str] = field(default_factory=list)
    details: dict = field(default_factory=dict)


# URL shorteners (hide the true destination) + obvious vectors.
_SUSPICIOUS_DOMAINS = {"bit.ly", "t.co", "tinyurl.com", "goo.gl", "ow.ly"}

# Prompt-injection: adversarial text trying to hijack the reading model.
_INJECTION = [
    re.compile(r"ignore\s+(all\s+)?previous\s+instructions", re.I),
    re.compile(r"ignore\s+(all\s+)?above", re.I),
    re.compile(r"you\s+are\s+now\s+(a|an)\s+", re.I),
    re.compile(r"system\s*:\s*you\s+are", re.I),
    re.compile(r"<\s*system\s*>", re.I),
    re.compile(r"disregard\s+(all|any|the)\s+", re.I),
    re.compile(r"new\s+instructions?\s*:", re.I),
    re.compile(r"forget\s+(everything|all|what)", re.I),
    re.compile(r"override\s+(the\s+)?system", re.I),
    re.compile(r"\[INST\]", re.I),
    re.compile(r"<\|im_start\|>", re.I),
]

# Fabrication signals — text that announces itself as machine-generated boilerplate.
_FABRICATION = [
    re.compile(r"(as an ai|as a language model|i cannot|i apologize)", re.I),
    re.compile(r"(generated by|written by)\s+(chatgpt|gpt|claude|gemini|ai)", re.I),
    re.compile(r"this\s+(article|text)\s+(was|is)\s+generated", re.I),
]

_SEO_SPAM = [
    re.compile(r"(click here|buy now|limited time|act now|free trial)", re.I),
    re.compile(r"(best|top|#1|number one)\s+\w+\s+(in|of|for)\s+\d{4}", re.I),
]


def _verdict(score: float) -> Verdict:
    if score >= 0.6:
        return Verdict.REJECT
    if score >= 0.3:
        return Verdict.FLAG
    return Verdict.PASS


def inspect_url(url: str) -> Inspection:
    """Score a URL before fetching."""
    if not url:
        return Inspection(Verdict.REJECT, 1.0, ["empty_url"])
    if url.startswith("data:"):
        return Inspection(Verdict.REJECT, 1.0, ["data_uri_blocked"])
    try:
        parsed = urlparse(url)
        domain = (parsed.hostname or "").lower()
    except Exception:
        return Inspection(Verdict.REJECT, 1.0, ["malformed_url"])
    flags: list[str] = []
    score = 0.0
    if parsed.scheme not in ("http", "https"):
        flags.append(f"unusual_protocol:{parsed.scheme}"); score += 0.3
    for sus in _SUSPICIOUS_DOMAINS:
        if domain == sus or domain.endswith("." + sus):
            flags.append(f"suspicious_domain:{sus}"); score += 0.4
    if re.match(r"^\d+\.\d+\.\d+\.\d+$", domain):
        flags.append("ip_based_url"); score += 0.3
    if len(url) > 2000:
        flags.append("excessively_long_url"); score += 0.2
    return Inspection(_verdict(score), score, flags)


def inspect_content(text: str, source_url: str = "") -> Inspection:
    """Score fetched content before a scout reads it / it enters memory."""
    if not text or len(text.strip()) < 10:
        return Inspection(Verdict.REJECT, 0.8, ["empty_or_trivial_content"])
    flags: list[str] = []
    score = 0.0
    details: dict = {}

    hits = sum(len(p.findall(text)) for p in _INJECTION)
    if hits:
        score += min(0.5, hits * 0.15)
        flags.append("prompt_injection")
        details["injection_matches"] = hits

    fab = sum(1 for p in _FABRICATION if p.search(text))
    if fab:
        score += min(0.3, fab * 0.1)
        flags.append("ai_generated_signal")
        details["fabrication_signals"] = fab

    seo = sum(1 for p in _SEO_SPAM if p.search(text))
    if seo >= 2:
        score += 0.2
        flags.append("seo_spam")

    if sum(1 for c in text if ord(c) > 0xFFF0) > 5:
        score += 0.1
        flags.append("suspicious_unicode")

    words = len(text.split())
    links = len(re.findall(r"https?://", text))
    if words > 0 and links / words > 0.1:
        score += 0.15
        flags.append("high_link_density")

    return Inspection(_verdict(score), round(score, 3), flags, details)


def inspect_search_results(results: list[dict]) -> list[dict]:
    """Inspect a batch of SearXNG results: drop REJECT, annotate the rest with ``_inspection``.

    Each result keeps its fields; survivors gain ``_inspection = {verdict, score, flags}`` so the
    caller can tier them (e.g. FLAG → private memory only). Mutates and returns the kept list.
    """
    kept: list[dict] = []
    for r in results:
        url = r.get("url", "")
        if inspect_url(url).verdict == Verdict.REJECT:
            continue
        ins = inspect_content(f"{r.get('title','')} {r.get('content','')}", source_url=url)
        if ins.verdict == Verdict.REJECT:
            continue
        r["_inspection"] = {"verdict": ins.verdict.value, "score": ins.score, "flags": ins.flags}
        kept.append(r)
    return kept
